### ISSUE TITLE
Green Screen when Generic is used

### ISSUE THREAD

**Issue by Druccy** [HopFlash/lootpeep#1]
Hi, I just installed this and my entire screen went green due to the overlay.
FIX:  go into Source Properties / Filters / add Chroma Key and it fixes it.

Just a heads up as it was not in notes and not everyone will know what to do - I noticed  Chroma in the file name and that is where I got the idea from to add the Chroma Key.

Thanks
Druccy

**Comment by HopFlash** [comment]
Hmm...I'm not sure if I understand your issue.

You don't need to use the generic overlay in OBS for this extension. You can use whatever you used before and if it is the generic overlay it should have been green before.
For this extension you need to have an extra chrome tab open with the generic overlay and if that is green or not it shouldn't disturb your stream because it's normally not your source for obs (ok, you could but that wouldn't been the best option to integrate the loots banner into obs anyways).

if I missed something please tell me ;)

**Comment by Druccy** [comment]
Hi HopFlash, I might be the one missing something, I'm new to this and a helper on loots discord, according to setup it says use GENERIC so I did lol, other will also do it so I thought if I put this here and on discord, it will save you and discord time telling people what to do if it happens. Mine works great so no problems my side. Thanks for the work you put into this.
Druccy

**Comment by HopFlash** [comment]
ok...but then I close the issue because there is no real problem ;)

But thanks for mentioned it because you are right if someone had not seen the green background yet it could be disturbing ;)
